Fix build on Mac OS X Snow Leopard
--HG--
extra : convert_revision : 18301b13ea1c4d3e9be069d8f17cf5394658e0d6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -641,9 +641,9 @@ ac_subst_vars='LTLIBOBJS
 LIBOBJS
 llvm_ldflags
 llvm_includedir
+llvm_target
 llvm_all_libs
 llvm_cppflags
-llvm_target
 EGREP
 GREP
 CPP
@@ -1322,6 +1322,9 @@ Fine tuning of the installation directories:
 _ACEOF
 
   cat <<\_ACEOF
+
+System types:
+  --target=TARGET   configure for building compilers for TARGET [guessed]
 _ACEOF
 fi
 
@@ -2496,14 +2499,40 @@ fi
 
 
 
+
+
+if test "$target" = ""
+then
+    if test "${compiler}" != ""
+    then
+        target=`${compiler} +RTS --info | grep '^ ,("Target platform"' | sed -e 's/.*, "//' -e 's/")//' | tr -d '\r'`
+        echo "Target platform inferred as: $target"
+    else
+        echo "Can't work out target platform"
+        exit 1
+    fi
+fi
+
+case $target in
+i386-apple-darwin)
+    TARGET_CPPFLAGS="-m32"
+    TAGRET_LDFLAGS="-m32"
+    ;;
+x86_64-apple-darwin)
+    TARGET_CPPFLAGS="-m64"
+    TAGRET_LDFLAGS="-m64"
+    ;;
+esac
+
 llvm_cppflags="`$llvm_config --cppflags`"
 llvm_includedir="`$llvm_config --includedir`"
 llvm_ldflags="`$llvm_config --ldflags`"
+
 llvm_all_libs="`$llvm_config --libs all`"
 llvm_target="`$llvm_config --libs engine | sed 's/.*LLVM\(.[^ ]*\)CodeGen.*/\1/'`"
 
-CPPFLAGS="$llvm_cppflags $CPPFLAGS"
-LDFLAGS="$llvm_ldflags $LDFLAGS"
+CPPFLAGS="$llvm_cppflags $CPPFLAGS $TARGET_CPPFLAGS"
+LDFLAGS="$llvm_ldflags $LDFLAGS $TARGET_LDFLAGS"
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -4050,6 +4079,7 @@ else
 $as_echo "$as_me: error: could not find LLVM C bindings" >&2;}
    { (exit 1); exit 1; }; }
 fi
+
 
 
 
